from __future__ import annotations

from .ai_vs_ai import (
    GPT_5_2_MODELS,
    _api_call_with_retry,
    _build_api_call_kwargs,
    _get_ai_client,
    _get_ai_model,
    _get_reasoning_effort,
    _is_gpt_5_2_model,
    generate_ai_vs_ai_reply,
    get_ai_vs_ai_status,
    is_ai_vs_ai_session,
    run_ai_vs_ai_turn,
)
from .prompt_context import (
    TASK_BACKGROUND,
    _ai_debug_enabled,
    _build_ai_messages_from_history,
    _build_director_conversation_state,
    _build_matcher_current_sequence_state_for_prompt,
    _compute_round_correct_count,
    _get_pending_refill_positions,
    _get_prompt_strategy_name,
    _inject_task_background,
    _is_acl_prompt_strategy,
    _is_instruction_message,
    _should_log_acl_reasoning,
)
from .sequence import _update_ai_partial_sequence
from .visual_context import (
    _build_ai_director_grid_composite,
    _build_ai_matcher_grid_composite,
    _build_round_feedback_image,
    _debug_save_ai_director_grid_image,
    _debug_save_ai_matcher_grid_image,
    _debug_save_round_feedback_image,
    _image_rel_to_data_url,
    _inject_round_feedback_context,
    _inject_visual_grid_context,
    _load_matcher_pool_image_urls,
    _load_shared_grid_image_urls,
    _resolve_static_image_path,
)

__all__ = [
    "GPT_5_2_MODELS",
    "TASK_BACKGROUND",
    "_ai_debug_enabled",
    "_api_call_with_retry",
    "_build_ai_director_grid_composite",
    "_build_ai_matcher_grid_composite",
    "_build_ai_messages_from_history",
    "_build_api_call_kwargs",
    "_build_director_conversation_state",
    "_build_matcher_current_sequence_state_for_prompt",
    "_build_round_feedback_image",
    "_compute_round_correct_count",
    "_debug_save_ai_director_grid_image",
    "_debug_save_ai_matcher_grid_image",
    "_debug_save_round_feedback_image",
    "_get_ai_client",
    "_get_ai_model",
    "_get_pending_refill_positions",
    "_get_prompt_strategy_name",
    "_get_reasoning_effort",
    "_image_rel_to_data_url",
    "_inject_round_feedback_context",
    "_inject_task_background",
    "_inject_visual_grid_context",
    "_is_acl_prompt_strategy",
    "_is_gpt_5_2_model",
    "_is_instruction_message",
    "_load_matcher_pool_image_urls",
    "_load_shared_grid_image_urls",
    "_resolve_static_image_path",
    "_should_log_acl_reasoning",
    "_update_ai_partial_sequence",
    "generate_ai_vs_ai_reply",
    "get_ai_vs_ai_status",
    "is_ai_vs_ai_session",
    "run_ai_vs_ai_turn",
]
